import io
from datetime import datetime, timezone
from collections import defaultdict
from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle, PageBreak

NAVY = colors.HexColor("#2C3E50")
TEAL = colors.HexColor("#4A90A4")
LIGHT_GRAY = colors.HexColor("#F5F6FA")
MID_GRAY = colors.HexColor("#7F8C8D")
BORDER_GRAY = colors.HexColor("#E0E0E0")
GREEN = colors.HexColor("#27AE60")
AMBER = colors.HexColor("#F39C12")
RED = colors.HexColor("#E74C3C")

class ReportTemplate(SimpleDocTemplate):
    def __init__(self, filename, group_name, user_name, **kw):
        super().__init__(
            filename, 
            pagesize=A4, 
            rightMargin=2.2*cm, 
            leftMargin=2.2*cm, 
            topMargin=2.5*cm, 
            bottomMargin=2*cm, 
            **kw
        )
        self.group_name = group_name
        self.user_name = user_name
        self.generation_time = datetime.now()

    def build_with_canvas(self, flowables):
        self.build(flowables, onFirstPage=self._header_footer, onLaterPages=self._header_footer)

    def _header_footer(self, canvas, doc):
        canvas.saveState()
        
        # HEADER (total 1.2cm from top)
        canvas.setStrokeColor(TEAL)
        canvas.setLineWidth(3)
        canvas.line(0, A4[1], A4[0], A4[1])
        
        canvas.setFillColor(NAVY)
        canvas.setFont("Helvetica-Bold", 9)
        canvas.drawString(2.2*cm, A4[1] - 0.8*cm, "CollabSpace")
        
        canvas.setFillColor(MID_GRAY)
        canvas.setFont("Helvetica", 9)
        canvas.drawRightString(A4[0] - 2.2*cm, A4[1] - 0.8*cm, self.group_name)
        
        canvas.setStrokeColor(BORDER_GRAY)
        canvas.setLineWidth(0.5)
        canvas.line(2.2*cm, A4[1] - 1.2*cm, A4[0] - 2.2*cm, A4[1] - 1.2*cm)
        
        # FOOTER (total 1cm from bottom)
        canvas.setStrokeColor(BORDER_GRAY)
        canvas.setLineWidth(0.5)
        canvas.line(2.2*cm, 1*cm, A4[0] - 2.2*cm, 1*cm)
        
        canvas.setFillColor(MID_GRAY)
        canvas.setFont("Helvetica", 8)
        canvas.drawString(2.2*cm, 0.6*cm, "Confidential \u2014 Generated by CollabSpace")
        
        canvas.drawRightString(A4[0] - 2.2*cm, 0.6*cm, f"Page {doc.page}")
        canvas.restoreState()

def add_section_heading(story, title):
    styles = getSampleStyleSheet()
    h_style = ParagraphStyle('SecH', fontName='Helvetica-Bold', fontSize=8, textColor=TEAL, spaceBefore=0, spaceAfter=0)
    spaced = " ".join(list(title.upper()))
    story.append(Spacer(1, 0.3*cm))
    story.append(Paragraph(spaced, h_style))
    story.append(Spacer(1, 0.1*cm))
    t = Table([['']], colWidths=[A4[0]-4.4*cm])
    t.setStyle(TableStyle([
        ('LINEABOVE', (0,0), (-1,-1), 1, TEAL), 
        ('BOTTOMPADDING', (0,0), (-1,-1), 0), 
        ('TOPPADDING', (0,0), (-1,-1), 0), 
        ('LEFTPADDING', (0,0), (-1,-1), 0)
    ]))
    story.append(t)
    story.append(Spacer(1, 0.4*cm))

def format_money(val):
    if val is None: val = 0
    return f"\u20B9{val:,.2f}"

def format_time(minutes):
    if not minutes: return "0h 0m"
    h = minutes // 60
    m = minutes % 60
    return f"{int(h)}h {int(m)}m"

def calculate_report_data(group):
    tasks = group.tasks.all()
    members = group.members.all()
    
    from app.models.activity import ActivityLog
    from datetime import datetime, timedelta, timezone
    
    now_utc = datetime.utcnow()
    thirty_days_ago = now_utc - timedelta(days=30)
    
    activities = ActivityLog.query.filter_by(group_id=group.id).filter(ActivityLog.created_at >= thirty_days_ago).order_by(ActivityLog.created_at.desc()).all()
    
    total_tasks = len(tasks)
    total_members = len(members)
    
    from app.utils.time_tracking import calculate_member_time_stats
    time_stats = calculate_member_time_stats(group.id)
    
    tasks_with_estimates = 0
    tasks_over_estimate = 0
    tasks_under_estimate = 0
    
    for tk in time_stats.get('by_task', []):
        if tk['estimated_minutes'] is not None:
            tasks_with_estimates += 1
            if tk['variance_status'] == 'under':
                tasks_under_estimate += 1
            elif tk['variance_status'] == 'over':
                tasks_over_estimate += 1
    
    time_stats['tasks_with_estimates'] = tasks_with_estimates
    time_stats['tasks_over_estimate'] = tasks_over_estimate
    time_stats['tasks_under_estimate'] = tasks_under_estimate
    time_stats['member_time_breakdown'] = time_stats.get('by_member', [])
    
    # Calculate New UI Metrics
    completed_tasks = sum(1 for t in tasks if t.is_completed)
    in_progress_tasks = sum(1 for t in tasks if not t.is_completed and t.status == 'in_progress')
    tasks_overdue = [t for t in tasks if t.deadline and t.deadline < now_utc and not t.is_completed]
    
    overall = {
        'total_tasks': total_tasks,
        'total_members': total_members,
        'completed_tasks': completed_tasks,
        'in_progress_tasks': in_progress_tasks,
        'tasks_overdue_count': len(tasks_overdue),
        'expense_count': 0,
        'total_expenses': 0.0,
        'report_period_start': thirty_days_ago.strftime('%d %b %Y'),
        'report_period_end': now_utc.strftime('%d %b %Y'),
    }

    task_timeline = []
    at_risk_tasks = []
    overdue_tasks_list = []
    
    for t in tasks:
        deadline_status = "No Deadline"
        days_variance = None
        
        if not t.deadline:
            deadline_status = "On Time" if t.is_completed else "Pending"
        else:
            if t.is_completed:
                # Use date objects or just compare if both naive
                cmp_completed = t.completed_at if t.completed_at else now_utc
                days_variance = (t.deadline.date() - cmp_completed.date()).days
                deadline_status = "On Time" if days_variance >= 0 else "Late"
            else:
                days_remaining = (t.deadline.date() - now_utc.date()).days
                if days_remaining < 0:
                    deadline_status = "Overdue"
                    overdue_tasks_list.append({'task': t, 'days_overdue': abs(days_remaining)})
                elif days_remaining <= 3:
                    deadline_status = "Pending"
                    at_risk_tasks.append({'task': t, 'days_remaining': days_remaining})
                else:
                    deadline_status = "Pending"
                    
        task_timeline.append({
            'task': t,
            'deadline_status': deadline_status,
            'days_variance': days_variance
        })
    task_timeline.sort(key=lambda x: x['task'].created_at or now_utc, reverse=True)

    member_performance = []
    for member in members:
        user_tasks = [t for t in tasks if t.assigned_to == member.user_id]
        assigned = len(user_tasks)
        completed = sum(1 for t in user_tasks if t.is_completed)
        on_time = sum(1 for t in user_tasks if t.is_completed and t.deadline and t.deadline.date() >= (t.completed_at or now_utc).date())
        on_time += sum(1 for t in user_tasks if t.is_completed and not t.deadline)
        late = completed - on_time
        overdue = sum(1 for t in user_tasks if not t.is_completed and t.deadline and t.deadline < now_utc)
        comp_rate = round((completed / assigned * 100) if assigned > 0 else 0)
        
        days_taken = [(t.completed_at - t.created_at).days for t in user_tasks if t.is_completed and t.completed_at and t.created_at]
        avg_days = round(sum(days_taken) / len(days_taken), 1) if days_taken else None
        
        grade = "Needs Improvement"
        if assigned == 0: grade = "No Tasks"
        elif comp_rate >= 80 and overdue == 0: grade = "Excellent"
        elif comp_rate >= 60: grade = "Good"
        elif comp_rate >= 40: grade = "Average"
        
        member_performance.append({
            'user': member.user, 'assigned': assigned, 'completed': completed,
            'on_time': on_time, 'late': late, 'overdue': overdue,
            'completion_rate': comp_rate, 'avg_days': avg_days, 'grade': grade
        })
    member_performance.sort(key=lambda x: x['completion_rate'], reverse=True)

    total_on_time = sum(mp['on_time'] for mp in member_performance)
    total_comp = sum(mp['completed'] for mp in member_performance)
    on_time_rate = round((total_on_time / total_comp * 100) if total_comp > 0 else 100)
    part_rate = round((sum(1 for mp in member_performance if mp['assigned'] > 0) / total_members * 100) if total_members > 0 else 0)
    comp_rate_all = round((completed_tasks / total_tasks * 100) if total_tasks > 0 else 0)
    
    health_score = round((comp_rate_all * 0.5) + (on_time_rate * 0.3) + (part_rate * 0.2))
    h_status = "Healthy" if health_score >= 80 else ("At Risk" if health_score >= 50 else "Critical")
    health = {
        'score': health_score, 'status': h_status, 'completion_rate': comp_rate_all,
        'on_time_rate': on_time_rate, 'participation_rate': part_rate
    }
    
    from collections import Counter
    actions_by_user = Counter(a.user_id for a in activities)
    most_active, peak_day = None, None
    if actions_by_user:
        act_id, act_count = actions_by_user.most_common(1)[0]
        u_member = next((m for m in members if m.user_id == act_id), None)
        if u_member: most_active = {'user': u_member.user, 'count': act_count}
        
    dates_count = Counter(a.created_at.strftime('%Y-%m-%d') for a in activities if a.created_at)
    if dates_count:
        p_date, p_count = dates_count.most_common(1)[0]
        peak_day = {'date': p_date, 'count': p_count}
        
    act_per_mem = [{'user': m.user, 'count': actions_by_user.get(m.user_id, 0)} for m in members]
    act_per_mem.sort(key=lambda x: x['count'], reverse=True)
    
    return {
        'group': group,
        'group_id': group.id,
        'group_name': group.name,
        'overall': overall,
        'health': health,
        'member_performance': member_performance,
        'task_timeline': task_timeline,
        'overdue_tasks': overdue_tasks_list,
        'at_risk_tasks': at_risk_tasks,
        'activity_summary': {'most_active': most_active, 'peak_day': peak_day, 'actions_per_member': act_per_mem},
        'tasks': tasks,
        'members': members,
        'activities': activities,
        'expenses': [],
        'time_stats': time_stats
    }


def generate_pdf_report(data):
    group_name = data.get('group_name', 'Group')
    user_name = data.get('generated_by').username if data.get('generated_by') else 'Unknown'
    
    buffer = io.BytesIO()
    doc = ReportTemplate(buffer, group_name, user_name)
    story = []
    styles = getSampleStyleSheet()
    normal_style = styles['Normal']
    
    overall = data.get('overall', {})
    health = data.get('health', {})
    member_perf = data.get('member_performance', [])
    task_timeline = data.get('task_timeline', [])
    overdue_tasks = data.get('overdue_tasks', [])
    at_risk_tasks = data.get('at_risk_tasks', [])
    activity_summary = data.get('activity_summary', {})
    time_stats = data.get('time_stats', {})
    has_time_data = bool(time_stats.get('by_task') or time_stats.get('by_member'))
    has_overdue = bool(overdue_tasks or at_risk_tasks)

    # Useful Paragraph Styles
    p_gray = ParagraphStyle('PGray', parent=normal_style, fontName='Helvetica', fontSize=9, textColor=MID_GRAY)
    p_gray_sm = ParagraphStyle('PGraySm', parent=normal_style, fontName='Helvetica', fontSize=8, textColor=MID_GRAY)
    p_gray_i = ParagraphStyle('PGrayI', parent=normal_style, fontName='Helvetica-Oblique', fontSize=9, textColor=MID_GRAY)
    p_navy = ParagraphStyle('PNavy', parent=normal_style, fontName='Helvetica', fontSize=9, textColor=NAVY)
    p_navy_b = ParagraphStyle('PNavyB', parent=normal_style, fontName='Helvetica-Bold', fontSize=9, textColor=NAVY)
    p_cen = ParagraphStyle('PCen', parent=normal_style, fontName='Helvetica', fontSize=9, textColor=NAVY, alignment=1)

    # ----------------------------------------------------
    # PAGE 1: COVER PAGE
    # ----------------------------------------------------
    story.append(Spacer(1, 3*cm))
    story.append(Paragraph(group_name, ParagraphStyle('T1', fontName='Helvetica-Bold', fontSize=28, textColor=NAVY, leading=34)))
    story.append(Paragraph("Student Report Card & Performance", ParagraphStyle('T2', fontName='Helvetica', fontSize=16, textColor=MID_GRAY, leading=20)))
    story.append(Spacer(1, 0.3*cm))
    story.append(Paragraph(f"Report Period: {overall.get('report_period_start', '')} \u2014 {overall.get('report_period_end', '')}", ParagraphStyle('T3', fontName='Helvetica', fontSize=10, textColor=MID_GRAY, leading=14)))
    story.append(Spacer(1, 0.5*cm))
    
    div_t = Table([['']], colWidths=[A4[0]-4.4*cm])
    div_t.setStyle(TableStyle([('LINEABOVE', (0,0), (-1,-1), 0.5, BORDER_GRAY), ('PADDING', (0,0), (-1,-1), 0)]))
    story.append(div_t)
    story.append(Spacer(1, 0.8*cm))

    # Calculate Grade based on Total Time Logged
    total_minutes = time_stats.get('total_minutes', 0)
    total_hours = total_minutes / 60.0
    
    if total_hours > 10:
        grade_letter = 'A'
        grade_color = GREEN
        g_desc = "Excellent time dedication. Keep up the good work!"
    elif total_hours >= 5:
        grade_letter = 'B'
        grade_color = AMBER
        g_desc = "Good effort, but there is room to invest more time into the project."
    else:
        grade_letter = 'C'
        grade_color = RED
        g_desc = "Insufficient time logged. Needs significant improvement immediately."

    left_col = [
        Paragraph("OVERALL PROJECT GRADE", ParagraphStyle('Lbl', fontName='Helvetica-Bold', fontSize=8, textColor=MID_GRAY, leading=10)),
        Spacer(1, 5),
        Paragraph(f"<font color='{grade_color.hexval()}'>Grade: {grade_letter}</font>", ParagraphStyle('Score', fontName='Helvetica-Bold', fontSize=40, leading=46)),
        Spacer(1, 5),
        Paragraph(g_desc, p_gray)
    ]
    
    right_inner = [
        [Paragraph("Time Logged", p_gray), Paragraph(f"<font color='{NAVY.hexval()}'>{format_time(total_minutes)}</font>", ParagraphStyle('SB', fontName='Helvetica-Bold', fontSize=11))],
        [Paragraph("Task Completion", p_gray), Paragraph(f"<font color='{NAVY.hexval()}'>{health.get('completion_rate', 0)}%</font>", ParagraphStyle('SB', fontName='Helvetica-Bold', fontSize=11))],
        [Paragraph("On-Time Rate", p_gray), Paragraph(f"<font color='{NAVY.hexval()}'>{health.get('on_time_rate', 0)}%</font>", ParagraphStyle('SB', fontName='Helvetica-Bold', fontSize=11))]
    ]
    t_right = Table(right_inner, colWidths=[3.5*cm, 2*cm])
    t_right.setStyle(TableStyle([
        ('LINEBELOW', (0,0), (-1,1), 0.5, BORDER_GRAY),
        ('PADDING', (0,0), (-1,-1), 5),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE')
    ]))
    
    health_t = Table([[left_col, t_right]], colWidths=[(A4[0]-4.4*cm)*0.6, (A4[0]-4.4*cm)*0.4])
    health_t.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,-1), LIGHT_GRAY),
        ('BOX', (0,0), (-1,-1), 1, BORDER_GRAY),
        ('VALIGN', (0,0), (-1,-1), 'TOP'),
        ('PADDING', (0,0), (-1,-1), 20)
    ]))
    story.append(health_t)
    story.append(Spacer(1, 0.8*cm))
    
    # Summary Boxes
    boxes = [
        [overall.get('total_tasks', 0), "Total", "Tasks"],
        [overall.get('completed_tasks', 0), "Completed", "Tasks"],
        [overall.get('in_progress_tasks', 0), "Pending", "Tasks"],
        [overall.get('tasks_overdue_count', 0), "Overdue", "Tasks"]
    ]
    
    box_cells = []
    box_w = (A4[0]-4.4*cm)/4
    for b in boxes:
        box_cells.append(
            Table([
                [Paragraph(f"{b[0]}", ParagraphStyle('Val', fontName='Helvetica-Bold', fontSize=24, textColor=NAVY, alignment=1, leading=28))],
                [Paragraph(b[1], ParagraphStyle('L1', fontName='Helvetica-Bold', fontSize=8, textColor=MID_GRAY, alignment=1, leading=10))],
                [Paragraph(b[2], ParagraphStyle('L2', fontName='Helvetica', fontSize=8, textColor=MID_GRAY, alignment=1, leading=10))]
            ], colWidths=[box_w])
        )
        
    sum_t = Table([box_cells], colWidths=[box_w]*4)
    sum_t.setStyle(TableStyle([
        ('BOX', (0,0), (-1,-1), 1, BORDER_GRAY),
        ('INNERGRID', (0,0), (-1,-1), 1, BORDER_GRAY),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('PADDING', (0,0), (-1,-1), 10)
    ]))
    story.append(sum_t)
    story.append(Spacer(1, 0.8*cm))
    story.append(div_t)
    story.append(Spacer(1, 0.5*cm))
    
    gen_time = datetime.now().strftime('%d %b %Y at %H:%M')
    story.append(Paragraph(f"Prepared by {user_name} on {gen_time}", p_gray))
    story.append(PageBreak())

    # ----------------------------------------------------
    # PAGE 2: TEAM PERFORMANCE
    # ----------------------------------------------------
    add_section_heading(story, "Team Performance")
    story.append(Paragraph("This section shows how each team member contributed to the project. Grades are based on task completion rate.", p_gray))
    story.append(Spacer(1, 0.3*cm))
    
    w_team = A4[0]-4.4*cm
    cw_team = [w_team*0.22, w_team*0.12, w_team*0.10, w_team*0.12, w_team*0.12, w_team*0.16, w_team*0.16]
    
    t_perf_data = [["Member", "Tasks Given", "Done", "On Time", "Overdue", "Completion", "Grade"]]
    tot_given, tot_done, tot_ontime, tot_overdue = 0, 0, 0, 0
    
    for mp in member_perf:
        tot_given += mp['assigned']
        tot_done += mp['completed']
        tot_ontime += mp['on_time']
        tot_overdue += mp['overdue']
        
        g = mp['grade']
        gc = NAVY
        if g == "Excellent": gc = GREEN
        elif g == "Good": gc = TEAL
        elif g == "Average": gc = AMBER
        elif g == "Needs Improvement": gc = RED
        
        comp_str = f"<font color='{gc.hexval()}'>{mp['completion_rate']}%</font>"
        grade_str = f"<font color='{gc.hexval()}'>{g}</font>"
        
        t_perf_data.append([
            Paragraph(getattr(mp['user'], 'username', 'Unknown'), p_navy),
            Paragraph(str(mp['assigned']), p_cen),
            Paragraph(str(mp['completed']), p_cen),
            Paragraph(str(mp['on_time']), p_cen),
            Paragraph(str(mp['overdue']), p_cen),
            Paragraph(comp_str, p_cen),
            Paragraph(grade_str, p_cen)
        ])
        
    t_perf_data.append([
        Paragraph("Team Total", p_navy_b),
        Paragraph(str(tot_given), p_cen),
        Paragraph(str(tot_done), p_cen),
        Paragraph(str(tot_ontime), p_cen),
        Paragraph(str(tot_overdue), p_cen),
        Paragraph(f"{round((tot_done/tot_given*100) if tot_given>0 else 0)}%", p_cen),
        ""
    ])
    
    t_perf = Table(t_perf_data, colWidths=cw_team, repeatRows=1)
    t_perf.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), NAVY),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 8),
        ('ALIGN', (0,0), (-1,0), 'CENTER'),
        ('ALIGN', (0,0), (0,0), 'LEFT'),
        ('ROWBACKGROUNDS', (0,1), (-1,-2), [colors.white, LIGHT_GRAY]),
        ('BACKGROUND', (0,-1), (-1,-1), LIGHT_GRAY),
        ('LINEABOVE', (0,-1), (-1,-1), 1, NAVY),
        ('GRID', (0,0), (-1,-1), 1, BORDER_GRAY),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('PADDING', (0,0), (-1,-1), 6)
    ]))
    story.append(t_perf)
    story.append(Spacer(1, 0.6*cm))
    
    if member_perf:
        top_perf = member_perf[0]
        if top_perf['completed'] > 0:
            story.append(Paragraph(f"{getattr(top_perf['user'], 'username', 'User')} was the top contributor with {top_perf['completed']} tasks completed at a {top_perf['completion_rate']}% completion rate.", p_gray_i))
            
    story.append(PageBreak())

    # ----------------------------------------------------
    # PAGE 3: TASK DETAILS
    # ----------------------------------------------------
    add_section_heading(story, "Task Breakdown")
    story.append(Paragraph("A complete list of all tasks, their current status, and whether they were completed on time.", p_gray_i))
    story.append(Spacer(1, 0.3*cm))
    
    w_task = A4[0]-4.4*cm
    cw_task = [w_task*0.28, w_task*0.16, w_task*0.12, w_task*0.14, w_task*0.14, w_task*0.16]
    
    t_task_data = [["Task Title", "Assigned To", "Status", "Deadline", "Completed On", "Result"]]
    
    def process_task(tt):
        t = tt['task']
        ds = tt['deadline_status']
        
        status_text = "To Do"
        status_color = MID_GRAY
        if t.is_completed: 
            status_text = "Done"
            status_color = GREEN
        elif t.status == 'in_progress': 
            status_text = "In Progress"
            status_color = AMBER
            
        res_color = MID_GRAY
        if ds == "On Time": res_color = GREEN
        elif ds == "Late": res_color = RED
        elif ds == "Overdue": res_color = RED
        elif ds == "Pending": res_color = AMBER
        
        res_str = f"<font color='{res_color.hexval()}'>{ds}</font>"
        if ds == "Overdue": res_str = f"<b>{res_str}</b>"
        
        dl_str = "\u2014"
        if t.deadline:
            dl_str = t.deadline.strftime('%d %b %Y')
            if ds == "Overdue": dl_str = f"<font color='{RED.hexval()}'>{dl_str}</font>"
            
        co_str = t.completed_at.strftime('%d %b %Y') if t.completed_at else "\u2014"
        
        return [
            Paragraph(t.title, p_navy),
            Paragraph(getattr(t.assignee, 'username', '\u2014') if t.assignee else '\u2014', p_navy),
            Paragraph(f"<font color='{status_color.hexval()}'>{status_text}</font>", p_cen),
            Paragraph(dl_str, p_cen),
            Paragraph(co_str, p_cen),
            Paragraph(res_str, p_cen)
        ]

    for tt in task_timeline:
        t_task_data.append(process_task(tt))
        
    if not task_timeline:
        t_task_data.append(["No tasks", "", "", "", "", ""])

    t_task = Table(t_task_data, colWidths=cw_task, repeatRows=1)
    t_task.setStyle(TableStyle([
        ('BACKGROUND', (0,0), (-1,0), NAVY),
        ('TEXTCOLOR', (0,0), (-1,0), colors.white),
        ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
        ('FONTSIZE', (0,0), (-1,0), 8),
        ('ALIGN', (0,0), (-1,0), 'CENTER'),
        ('ALIGN', (0,0), (1,0), 'LEFT'),
        ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, LIGHT_GRAY]),
        ('GRID', (0,0), (-1,-1), 1, BORDER_GRAY),
        ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
        ('PADDING', (0,0), (-1,-1), 6)
    ]))
    story.append(t_task)
    story.append(Spacer(1, 0.6*cm))
    
    # Quick stats
    on_time = sum(1 for tt in task_timeline if tt['deadline_status'] == "On Time")
    total_t = len(task_timeline)
    
    days_taken_abs = [(tt['task'].completed_at - tt['task'].created_at).days for tt in task_timeline if tt['task'].is_completed and tt['task'].completed_at and tt['task'].created_at]
    
    avg_days = sum(days_taken_abs)//len(days_taken_abs) if days_taken_abs else 0
    max_days = max(days_taken_abs) if days_taken_abs else 0
    
    stat_str = f"Tasks completed on time: {on_time} of {total_t}  |  Average completion time: {avg_days} days  |  Longest task: {max_days} days"
    story.append(Paragraph(stat_str, ParagraphStyle('QStats', fontName='Helvetica', fontSize=9, textColor=MID_GRAY, alignment=1, leading=12)))
    
    # ----------------------------------------------------
    # PAGE 4: ATTENTION REQUIRED
    # ----------------------------------------------------
    if has_overdue:
        story.append(PageBreak())
        add_section_heading(story, "Attention Required")
        
        if overdue_tasks:
            story.append(Paragraph("OVERDUE TASKS", ParagraphStyle('OvdH', fontName='Helvetica-Bold', fontSize=8, textColor=RED, leading=10)))
            story.append(Spacer(1, 0.2*cm))
            o_data = [["Task", "Assigned To", "Was Due", "Days Overdue"]]
            for ot in overdue_tasks:
                t = ot['task']
                d_past = ot['days_overdue']
                d_str = "1 day ago" if d_past == 1 else f"{d_past} days ago"
                o_data.append([
                    Paragraph(t.title, p_navy),
                    Paragraph(getattr(t.assignee, 'username', '\u2014') if t.assignee else '\u2014', p_navy),
                    Paragraph(t.deadline.strftime('%d %b %Y') if t.deadline else "\u2014", p_navy),
                    Paragraph(f"<b><font color='{RED.hexval()}'>{d_str}</font></b>", p_navy)
                ])
            
            ot_t = Table(o_data, colWidths=[w_task*0.4, w_task*0.2, w_task*0.2, w_task*0.2], repeatRows=1)
            ot_t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), RED),
                ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
                ('FONTSIZE', (0,0), (-1,0), 8),
                ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#FFF5F5")]),
                ('GRID', (0,0), (-1,-1), 1, BORDER_GRAY),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('PADDING', (0,0), (-1,-1), 6)
            ]))
            story.append(ot_t)
            story.append(Spacer(1, 0.4*cm))
            
        if at_risk_tasks:
            story.append(Paragraph("DUE WITHIN 3 DAYS", ParagraphStyle('RskH', fontName='Helvetica-Bold', fontSize=8, textColor=AMBER, leading=10)))
            story.append(Spacer(1, 0.2*cm))
            ar_data = [["Task", "Assigned To", "Due Date", "Days Left"]]
            for rt in at_risk_tasks:
                t = rt['task']
                d_left = rt['days_remaining']
                d_str = "1 day" if d_left == 1 else ("Due today" if d_left == 0 else f"{d_left} days")
                ar_data.append([
                    Paragraph(t.title, p_navy),
                    Paragraph(getattr(t.assignee, 'username', '\u2014') if t.assignee else '\u2014', p_navy),
                    Paragraph(t.deadline.strftime('%d %b %Y') if t.deadline else "\u2014", p_navy),
                    Paragraph(f"<b><font color='{AMBER.hexval()}'>{d_str}</font></b>", p_navy)
                ])
            ar_t = Table(ar_data, colWidths=[w_task*0.4, w_task*0.2, w_task*0.2, w_task*0.2], repeatRows=1)
            ar_t.setStyle(TableStyle([
                ('BACKGROUND', (0,0), (-1,0), AMBER),
                ('TEXTCOLOR', (0,0), (-1,0), colors.white),
                ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
                ('FONTSIZE', (0,0), (-1,0), 8),
                ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, colors.HexColor("#FFFBF0")]),
                ('GRID', (0,0), (-1,-1), 1, BORDER_GRAY),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
                ('PADDING', (0,0), (-1,-1), 6)
            ]))
            story.append(ar_t)

    # ----------------------------------------------------
    # PAGE 5: TIME & ACTIVITY
    # ----------------------------------------------------
    if has_time_data or data.get('activities'):
        story.append(PageBreak())
        add_section_heading(story, "Time & Activity Summary")
        story.append(Paragraph("This section shows how much time the team spent on the project and who was most active.", p_gray))
        story.append(Spacer(1, 0.4*cm))
        
        # Time Overview Row
        t_tot = time_stats.get('total_formatted', "0h 0m")
        t_active = activity_summary.get('most_active', {})
        t_active_name = t_active.get('user', {}).username if isinstance(t_active, dict) and t_active.get('user') else "None"
        t_per_mem = format_time(time_stats.get('total_minutes', 0) // len(member_perf) if member_perf else 0)
        
        t_boxes = [
            [t_tot, "Total Hours", "Logged"],
            [t_active_name, "Most Active", "Member"],
            [t_per_mem, "Average", "Per Member"]
        ]
        
        t_box_cells = []
        t_box_w = (A4[0]-4.4*cm)/3
        for b in t_boxes:
            t_box_cells.append(
                Table([
                    [Paragraph(f"{b[0]}", ParagraphStyle('ValTime', fontName='Helvetica-Bold', fontSize=18, textColor=NAVY, alignment=1, leading=22))],
                    [Paragraph(b[1], ParagraphStyle('L1Time', fontName='Helvetica-Bold', fontSize=8, textColor=MID_GRAY, alignment=1, leading=10))],
                    [Paragraph(b[2], ParagraphStyle('L2Time', fontName='Helvetica', fontSize=8, textColor=MID_GRAY, alignment=1, leading=10))]
                ], colWidths=[t_box_w])
            )
            
        time_sum_t = Table([t_box_cells], colWidths=[t_box_w]*3)
        time_sum_t.setStyle(TableStyle([
            ('BOX', (0,0), (-1,-1), 1, BORDER_GRAY),
            ('INNERGRID', (0,0), (-1,-1), 1, BORDER_GRAY),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('PADDING', (0,0), (-1,-1), 10)
        ]))
        story.append(time_sum_t)
        story.append(Spacer(1, 0.5*cm))
        
        tm_data = [["Member", "Hours Logged", "Tasks Worked On", "% of Total Time"]]
        total_mins = time_stats.get('total_minutes', 0)
        for tm in time_stats.get('by_member', []):
            pct = round((tm['total_minutes'] / total_mins * 100) if total_mins > 0 else 0)
            tm_data.append([
                Paragraph(tm.get('username', 'Unknown'), p_navy),
                Paragraph(format_time(tm['total_minutes']), p_cen),
                Paragraph(str(tm['task_count']), p_cen),
                Paragraph(f"{pct}%", p_cen)
            ])
            
        if not time_stats.get('by_member'):
            tm_data.append(["No time logged", "0h 0m", "0", "0%"])
            
        tm_t = Table(tm_data, colWidths=[w_task*0.4, w_task*0.2, w_task*0.2, w_task*0.2], repeatRows=1)
        tm_t.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), NAVY),
            ('TEXTCOLOR', (0,0), (-1,0), colors.white),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('FONTSIZE', (0,0), (-1,0), 8),
            ('ALIGN', (0,0), (-1,0), 'CENTER'),
            ('ALIGN', (0,0), (0,0), 'LEFT'),
            ('ROWBACKGROUNDS', (0,1), (-1,-1), [colors.white, LIGHT_GRAY]),
            ('GRID', (0,0), (-1,-1), 1, BORDER_GRAY),
            ('VALIGN', (0,0), (-1,-1), 'MIDDLE'),
            ('PADDING', (0,0), (-1,-1), 6)
        ]))
        story.append(tm_t)
        story.append(Spacer(1, 0.5*cm))
        
        story.append(Paragraph("RECENT ACTIVITY", ParagraphStyle('ActH', fontName='Helvetica-Bold', fontSize=8, textColor=MID_GRAY)))
        story.append(Spacer(1, 0.2*cm))
        
        for act in data.get('activities', [])[:20]:
            act_user = getattr(act.user, 'username', 'Unknown') if hasattr(act, 'user') else (getattr(act.member.user, 'username', 'Unknown') if hasattr(act, 'member') and getattr(act, 'member') else 'System')
            ad = act.created_at.strftime('%d Mar, %I:%M %p') if act.created_at else ''
            
            act_t_data = [[
                Paragraph(ad, p_gray),
                Paragraph(act_user, p_navy_b),
                Paragraph(act.description, p_navy)
            ]]
            act_tb = Table(act_t_data, colWidths=[w_task*0.14, w_task*0.20, w_task*0.66])
            act_tb.setStyle(TableStyle([
                ('PADDING', (0,0), (-1,-1), 3),
                ('VALIGN', (0,0), (-1,-1), 'MIDDLE')
            ]))
            story.append(act_tb)

    doc.build_with_canvas(story)
    buffer.seek(0)
    return buffer
