"""add_student_academic_profile_fields

Revision ID: 216db293d8e9
Revises: f8740d5e6329
Create Date: 2026-04-15 15:12:14.685881

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '216db293d8e9'
down_revision = 'f8740d5e6329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_academic_profiles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('semester', sa.Integer(), nullable=True),
    sa.Column('branch', sa.String(length=100), nullable=True),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('enrollment_number', sa.String(length=100), nullable=True),
    sa.Column('admission_year', sa.Integer(), nullable=True),
    sa.Column('linkedin_url', sa.String(length=300), nullable=True),
    sa.Column('github_url', sa.String(length=300), nullable=True),
    sa.Column('skills', sa.JSON(), nullable=True),
    sa.Column('availability_hours_per_week', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_academic_profiles')
    # ### end Alembic commands ###
