"""add user notification prefs

Revision ID: 715824e24b13
Revises: 67cfb92c048c
Create Date: 2026-04-04 22:57:41.873189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '715824e24b13'
down_revision = '67cfb92c048c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_notification_prefs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('task_assignment_emails', sa.Boolean(), nullable=True),
    sa.Column('deadline_reminder_emails', sa.Boolean(), nullable=True),
    sa.Column('weekly_summary_emails', sa.Boolean(), nullable=True),
    sa.Column('member_joined_emails', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_notification_prefs')
    # ### end Alembic commands ###
