"""Add time tracking models

Revision ID: d3537a3bc3f2
Revises: dd7342e346cb
Create Date: 2026-04-05 15:43:34.997761

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3537a3bc3f2'
down_revision = 'dd7342e346cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_by', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('split_type', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('note', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_expenses_paid_by_users', 'users', ['paid_by'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint('fk_expenses_paid_by_users', type_='foreignkey')
        batch_op.drop_column('note')
        batch_op.drop_column('split_type')
        batch_op.drop_column('paid_by')

    # ### end Alembic commands ###
