"""add_timer_fields_to_timelog

Revision ID: ea4693ec8c96
Revises: ffef1a8cfb36
Create Date: 2026-04-15 15:01:26.642998

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea4693ec8c96'
down_revision = 'ffef1a8cfb36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timer_start', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('is_running', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('time_logs', schema=None) as batch_op:
        batch_op.drop_column('is_running')
        batch_op.drop_column('timer_start')

    # ### end Alembic commands ###
