"""add_student_score_model

Revision ID: f8740d5e6329
Revises: ea4693ec8c96
Create Date: 2026-04-15 15:09:35.053342

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f8740d5e6329'
down_revision = 'ea4693ec8c96'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('student_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('group_id', sa.Integer(), nullable=False),
    sa.Column('sprint_label', sa.String(length=50), nullable=True),
    sa.Column('tasks_score', sa.Float(), nullable=True),
    sa.Column('hours_score', sa.Float(), nullable=True),
    sa.Column('peer_score', sa.Float(), nullable=True),
    sa.Column('mentor_rating', sa.Float(), nullable=True),
    sa.Column('final_score', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ),
    sa.ForeignKeyConstraint(['student_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('student_scores')
    # ### end Alembic commands ###
