"""RBAC and Rename Friend

Revision ID: ffef1a8cfb36
Revises: 7dec45626c86
Create Date: 2026-04-14 23:05:08.780801

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ffef1a8cfb36'
down_revision = '7dec45626c86'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.rename_table('friend_requests', 'member_connections')
    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approval_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('approved_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('approval_note', sa.Text(), nullable=True))
        batch_op.create_foreign_key('fk_tasks_approved_by_users', 'users', ['approved_by'], ['id'])

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('account_type', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('account_type')

    with op.batch_alter_table('tasks', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_approved_by_users', type_='foreignkey')
        batch_op.drop_column('approval_note')
        batch_op.drop_column('approved_at')
        batch_op.drop_column('approved_by')
        batch_op.drop_column('approval_status')

    op.rename_table('member_connections', 'friend_requests')
    # ### end Alembic commands ###
